name: dgcode
channels:
  - nodefaults
  - conda-forge
dependencies:
  - compilers
  - bash
  - simple-build-system
  - ncrystal
  - mcpl
  - matplotlib
  - zlib
  - geant4
  - expat
  - openscenegraph
  - scipy
  - hdf5
  - pysimplegui
  - pip
  - pip:
    - simple-build-dgcode
