name: dgcode
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python
###The preceding line will be edited for python version in .github/workflows/condatest.yml
  - compilers
  - bash
  - simple-build-system
  - ncrystal
  - matplotlib
  - zlib
  - geant4
  - expat
  - openscenegraph
  - scipy
  - hdf5
  - pysimplegui
  - pip
  # Do not install ourselves, since we will be testing the current source code,
  # not a prebuilt package:
  #  - pip:
  #    - simple-build-dgcode
  #
